# Generated by Django 3.1.5 on 2021-07-29 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alram_station', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('active_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('water_station', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('station_update', models.CharField(default='y', max_length=2)),
                ('first_warning', models.IntegerField()),
                ('second_warning', models.IntegerField()),
                ('station_URL', models.CharField(
                    default='malawi.cbfews.com', max_length=255)),
                ('low_level', models.IntegerField(default=0)),
                ('higer_level', models.IntegerField(
                    default=0, verbose_name='high level')),
                ('qc_level', models.IntegerField(verbose_name='threshold value')),
                ('alert_interval', models.IntegerField(
                    null=True, verbose_name='alert interval in minutes')),
                ('station_height', models.IntegerField()),
                ('gprs_APN', models.CharField(default='internet', max_length=255)),
                ('gprs_user', models.CharField(default='myName', max_length=100)),
                ('gprs_password', models.CharField(
                    default='myPass', max_length=100)),
                ('gprs_filter', models.CharField(default='1', max_length=20)),
                ('district', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='stations.district')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.BigIntegerField(blank=True, null=True)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StationData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('packetID', models.IntegerField()),
                ('receivedDate', models.DateTimeField()),
                ('depthValue', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('wf', models.IntegerField()),
                ('wdate', models.DateField(default='2010-01-01')),
                ('wTime', models.TimeField(default='00:00')),
                ('isSpike', models.IntegerField(default=0)),
                ('isProcessed', models.IntegerField(default=0)),
                ('last_alert_time', models.DateTimeField(blank=True, null=True)),
                ('alert_status', models.CharField(max_length=255)),
                ('station', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
            ],
        ),
        migrations.CreateModel(
            name='AlramData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('siren_triggered_at', models.DateTimeField()),
                ('alram', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='stations.alram')),
            ],
        ),
    ]
