# Generated by Django 3.2 on 2021-12-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [

        migrations.AddField(
            model_name='station',
            name='reach_id',
            field=models.IntegerField(default=7088812),
            preserve_default=False,
        ),
    ]
